# Generated by Django 4.1.3 on 2022-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_type', models.CharField(choices=[('tech', 'food')], max_length=100)),
                ('desciption', models.CharField(max_length=400)),
            ],
        ),
    ]
