# Generated by Django 4.1.3 on 2022-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(max_length=100),
        ),
    ]
