# Generated by Django 4.1.3 on 2022-12-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_options_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Tech')]),
        ),
    ]
