# Generated by Django 4.1.3 on 2022-12-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        
    ]
