# Generated by Django 4.1.3 on 2022-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(choices=[(1, 'Kleinstunternehmen'), (10, 'Kleinunternehmen'), (50, 'mittleres Unternehmen'), (250, 'Großunternehmen')]),
        ),
    ]
