# Generated by Django 4.1.3 on 2022-12-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
