# Generated by Django 4.1.3 on 2022-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companytype_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='employee_count',
            new_name='company_size',
        ),
        migrations.AlterField(
            model_name='companytype',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
