# Generated by Django 4.1.3 on 2022-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_employee_count_company_company_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('Kleinstunternehmen', 'Smallest'), ('Kleinunternehmen', 'Small'), ('mittleres Unternehmen', 'Medium'), ('Großunternehmen', 'Large')], max_length=100),
        ),
    ]
