# Generated by Django 4.1.3 on 2022-12-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_company_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('Kleinstunternehmen (<10 Beschäftigte)', 'Smallest'), ('Kleinunternehmen (10-49 Beschäftigte)', 'Small'), ('mittleres Unternehmen(50-249 Beschäftigte)', 'Medium'), ('Großunternehmen(250+ Beschäftigte)', 'Large')], max_length=100),
        ),
    ]
